/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.linked.list;

public class Library {
    public static void main(String[] args) {
     Linkedlist ls = new Linkedlist(new Node(10));
     ls.insert(11);
     ls.insert(12);
     System.out.println(ls);


        // Search in linked list
         if(ls.search(ls.head,20)){
               System.out.println("True");
         }else{
           System.out.println("False");
         }

    }
}
