/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.linked.list;
public class Library {
    public static void main(String[] args) {
        LinkedList<Integer> ls = new LinkedList<>();
        ls.insert(2);
        ls.insert(4);
        ls.insert(5);
        ls.insertBefore(5 , 1);
        System.out.println(ls);
//        ls.append(12);
//        ls.insertAfter(4 , 9);
//        ls.insertBefore(12 , 5);
//        System.out.println(ls.search(20));
//        System.out.println(ls.head.value);
    }
}