/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.HashTable;

public class App {
    public static void main(String[] args) {
        HashTable<String, Integer> hashList = new HashTable<>();
        hashList.add("A", 1);
        hashList.add("B", 2);
        hashList.add("C", 3);
        hashList.add("D", 4);

        System.out.println("The size is => " + hashList.getSize());
        System.out.println("The B allowance is => " + hashList.get("B"));
        System.out.println("Contain ss => " + hashList.contains("ss"));
        System.out.println("The size is => " + hashList.getSize());
    }
}
