/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.graphs;

import main.java.graphs.Graph;
import org.junit.Test;

import static org.junit.Assert.*;


public class AppTest {

    @Test
    public void addVertex(){

        Graph graph = new Graph();

        graph.addVertex("A");
        graph.addVertex("B");

        assertNotNull(graph.getVertices());
        assertEquals(2,graph.size());
    }

    @Test
    public void addEdge(){

        Graph graph = new Graph();

        graph.addVertex("A");
        graph.addVertex("B");
        graph.addEdge("A", "B");

        assertEquals("Vertex{label='A'}[Vertex{label='B'}]Vertex{label='B'}[Vertex{label='A'}]", graph.printGraph());
    }

    @Test
    public void vertexNeighbors(){

        Graph graph = new Graph();

        graph.addVertex("A");
        graph.addVertex("B");
        graph.addVertex("C");
        graph.addVertex("D")
        ;
        graph.addEdge("A", "C");
        graph.addEdge("A", "B");
        graph.addEdge("C", "B");

        assertEquals("[Vertex{label='C'}, Vertex{label='B'}]",graph.getNeighbors("A").toString());
        assertEquals("[Vertex{label='A'}, Vertex{label='B'}]", graph.getNeighbors("C").toString());

    }


    @Test
    public void emptyGraph(){

        Graph graph = new Graph();
        assertEquals(0,graph.size());
        assertEquals("[]", graph.getVertices().toString());
    }

    @Test
    public void removeVertex(){

        Graph graph = new Graph();

        graph.addVertex("A");
        graph.addVertex("D");
        graph.addEdge("A", "D");
        assertEquals("Vertex{label='A'}[Vertex{label='D'}]Vertex{label='D'}[Vertex{label='A'}]",graph.printGraph());
        assertEquals(2, graph.size());

        graph.removeVertex("A");
        assertEquals("Vertex{label='D'}[]",graph.printGraph());
        assertEquals(1, graph.size());
    }
    @Test
    public void oneVertexAndOneEdge(){
        Graph graph = new Graph();

        graph.addVertex("A");
        graph.removeEdge("A","A");

        assertEquals("Vertex{label='A'}[]",graph.printGraph());
    }

    @Test
    public void removeEdge(){
        Graph graph = new Graph();

        graph.addVertex("A");
        graph.addVertex("D");
        graph.addEdge("A", "D");
        assertEquals("Vertex{label='A'}[Vertex{label='D'}]Vertex{label='D'}[Vertex{label='A'}]",graph.printGraph());

        graph.removeEdge("D", "A");
        assertEquals("Vertex{label='A'}[]Vertex{label='D'}[]", graph.printGraph());
    }


}

