/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.Insertion.Sort;

import main.java.linked.list.Library;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

}
