/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.HashTable;

import static main.java.HashTable.FirstRepeated.findFirstRepeated;

public class App {
    public static void main(String[] args) {
//        HashTable<String, Integer> hashList = new HashTable<>();
//        hashList.add("A", 1);
//        hashList.add("B", 2);
//        hashList.add("C", 3);
//        hashList.add("D", 4);
//
//        System.out.println("The size is => " + hashList.getSize());
//        System.out.println("The B allowance is => " + hashList.get("B"));
//        System.out.println("Contain ss => " + hashList.contains("ss"));
//        System.out.println("The size is => " + hashList.getSize());

        String s1 = "Once a upon time, there was a brave princess who";
        String s2= "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        String s3="It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";


        System.out.println("First repeated word is :" + findFirstRepeated(s1));
        System.out.println("First repeated word is :" + findFirstRepeated(s2));
        System.out.println("First repeated word is :" + findFirstRepeated(s3));

    }
}
