/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.Merge_sort;

import main.java.Merge_sort.App;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void mergeSortTest1(){

        int [] arr = {1,4,2,8,3,9,0};
        App mergeSort = new App();
        mergeSort.mergeSort(arr,arr.length);
        assertEquals("[0, 1, 2, 3, 4, 8, 9]", Arrays.toString(arr));
    }
}
