/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.HashTable;

import main.java.HashTable.HashTable;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void TestContainsEmpty() {
        HashTable<String, Integer> hashList = new HashTable<>();
        assertTrue(hashList.isEmpty());
    }

    @Test
    public void TestContains() {
        HashTable<String, Integer> hashList = new HashTable<>();
        hashList.add("A",1);
        assertTrue(hashList.contains("A"));
    }

    @Test
    public void TestGetSize() {
        HashTable<String, Integer> hashList = new HashTable<>();

        hashList.add("A",1);
        assertEquals(1,hashList.getSize());

        hashList.add("B", 2);
        assertEquals(2,hashList.getSize());

    }
}
