package main.java.graphs;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
//        Graph graph = new Graph();
//
//        graph.addVertex("A");
//        graph.addVertex("B");
//        graph.addVertex("C");
//        graph.addVertex("D");
//
//        graph.addEdge("C", "D");
//        graph.addEdge("A", "B");
//        graph.addEdge("A", "C");
//
//        System.out.println("the graph => " + graph.printGraph());
//        System.out.println("the size => " + graph.size());
//
//        System.out.println(graph.dft(graph, "C"));
//
//        System.out.println(graph.getNeighbors("A"));
//
//        System.out.println(graph.getVertices());


        Graph graphs = new Graph();

        graphs.addVertex("Pandora");
        graphs.addVertex("Arendelle");
        graphs.addVertex("Metroville");
        graphs.addVertex("Monstroplolis");
        graphs.addVertex("Narnia");
        graphs.addVertex("Naboo");

        graphs.addEdge("Pandora", "Arendelle");
        graphs.addEdge("Arendelle", "Metroville");
        graphs.addEdge("Arendelle", "Monstroplolis");
        graphs.addEdge("Metroville", "Narnia");
        graphs.addEdge("Metroville", "Naboo");
        graphs.addEdge("Metroville", "Monstroplolis");
        graphs.addEdge("Monstroplolis", "Naboo");
        graphs.addEdge("Narnia", "Naboo");


      //  System.out.println(graphs.breadthTraverse( "Pandora"));



        graphs.addVertex("Pandora");
        graphs.addVertex("Arendelle");
        graphs.addVertex("Metroville");
        graphs.addVertex("Monstroplolis");
        graphs.addVertex("Narnia");
        graphs.addVertex("Naboo");

        graphs.addEdgeWithWeight("Pandora", "Monstroplolis", 100);
        graphs.addEdgeWithWeight("Arendelle", "Metroville",200);
        graphs.addEdgeWithWeight("Metroville", "Monstroplolis",300);
        graphs.addEdgeWithWeight("Narnia", "Narnia",400);
        graphs.addEdgeWithWeight("Naboo", "Metroville",500);
        graphs.addEdgeWithWeight("Metroville", "Monstroplolis",600);
        graphs.addEdgeWithWeight("Monstroplolis", "Naboo",700);
        graphs.addEdgeWithWeight("Arendelle", "Naboo",800);

        List<String> cities = new ArrayList<>();
        cities.add("Arendelle");
        cities.add("Metroville");

//        System.out.println(graphs.businessTrip(graphs,cities));


        graphs.addVertex("A");
        graphs.addVertex("B");
        graphs.addVertex("C");
        graphs.addVertex("D");
        graphs.addVertex("E");
        graphs.addVertex("F");
        graphs.addVertex("G");
        graphs.addVertex("H");

        graphs.addEdge("A", "D");
        graphs.addEdge("A", "B");
        graphs.addEdge("B", "D");
        graphs.addEdge("B", "C");
        graphs.addEdge("C", "G");
        graphs.addEdge("D", "F");
        graphs.addEdge("D", "H");
        graphs.addEdge("D", "E");
        graphs.addEdge("F", "H");

        System.out.println("Depth first ---> " + graphs.depthFirstTraverse("A"));
    }
}
