package main.java.graphs;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public static void main(String[] args) {
//        Graph graph = new Graph();
//
//        graph.addVertex("A");
//        graph.addVertex("B");
//        graph.addVertex("C");
//        graph.addVertex("D");
//
//        graph.addEdge("C", "D");
//        graph.addEdge("A", "B");
//        graph.addEdge("A", "C");
//
//        System.out.println("the graph => " + graph.printGraph());
//        System.out.println("the size => " + graph.size());
//
//        System.out.println(graph.dft(graph, "C"));
//
//        System.out.println(graph.getNeighbors("A"));
//
//        System.out.println(graph.getVertices());


        Graph graphs = new Graph();

        graphs.addVertex("Pandora");
        graphs.addVertex("Arendelle");
        graphs.addVertex("Metroville");
        graphs.addVertex("Monstroplolis");
        graphs.addVertex("Narnia");
        graphs.addVertex("Naboo");

        graphs.addEdge("Pandora", "Arendelle");
        graphs.addEdge("Arendelle", "Metroville");
        graphs.addEdge("Arendelle", "Monstroplolis");
        graphs.addEdge("Metroville", "Narnia");
        graphs.addEdge("Metroville", "Naboo");
        graphs.addEdge("Metroville", "Monstroplolis");
        graphs.addEdge("Monstroplolis", "Naboo");
        graphs.addEdge("Narnia", "Naboo");


        System.out.println(graphs.breadthTraverse( "Pandora"));

    }
}
