/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.stack.and.queue;

import main.java.stack.and.queue.QueueLinkedList;
import main.java.stack.and.queue.StackLinkedList;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    private static final StackLinkedList<Integer> testStack = new StackLinkedList<>();
    private static final QueueLinkedList<Integer> testQueue = new QueueLinkedList<>();


    @Test
    public void testStackPush() {
    testStack.push(1);
    testQueue.enqueue(1);
    assertEquals("Error with Stack Insertion:\n ", "{ 1 } -> NULL", String.valueOf(testStack));
}


    @Test
    public void testMultiplePush() {
        testStack.push(1);
        testStack.push(2);
        testStack.push(3);
        testStack.push(4);
        testQueue.enqueue(1);
        assertEquals(
                "Error with Stack Insertion:\n ",
                "{ 4 } -> { 3 } -> { 2 } -> { 1 } -> NULL",
                String.valueOf(testStack)
        );
    }

    @Test
    public void testPop() {
        testStack.push(1);
        testStack.pop();
        assertEquals("Error with Stack Insertion:\n ", "NUll", String.valueOf(testStack));
    }

    @Test
    public void testMultiplePop() {
        testStack.push(1);
        testStack.push(2);
        testStack.push(3);
        testStack.push(4);
        testStack.pop();
        testStack.pop();
        testStack.pop();
        testStack.pop();
        assertEquals("Error with Stack Insertion:\n ", "NUll", String.valueOf(testStack));
    }

    @Test
    public void testStackPeek() {
        testStack.push(1);
        testStack.push(2);
        assertEquals(
                "Error with Stack peek:\n ",
                2,
                testStack.peek()
        );

    }

    @Test
    public void testStackPeekEmpty() {
        assertEquals(
                "Error with peek on empty:\n ",
                -2147483648,
                testStack.peek()
        );
    }
    @Test
    public void testEnqueue() {
        testQueue.enqueue(1);
        assertEquals("Error add to queue:\n ", "{ 1 } -> NULL", String.valueOf(testQueue));
    }

    @Test
    public void testMultipleInsert() {
        testQueue.enqueue(1);
        testQueue.enqueue(2);
        testQueue.enqueue(3);
        testQueue.enqueue(4);
        assertEquals(
                "Error add multiple values to queue:\n ", "{ 1 } -> { 2 } -> { 3 } -> { 4 } -> NULL", String.valueOf(testQueue) );
    }

    @Test
    public void testDequeue() {
        testQueue.enqueue(1);
        testQueue.dequeue();
        assertEquals("Error delete from queue:\n ", "NUll", String.valueOf(testStack));
    }

    @Test
    public void testMultipleDequeue() {
        testQueue.enqueue(1);
        testQueue.enqueue(2);
        testQueue.enqueue(3);
        testQueue.enqueue(4);
        testQueue.dequeue();
        testQueue.dequeue();
        testQueue.dequeue();
        testQueue.dequeue();
        assertEquals("Error delete multiple values:\n ", "NUll", String.valueOf(testStack));
    }

    @Test
    public void testQueuePeek() {
        testQueue.enqueue(1);
        testQueue.enqueue(2);
        assertEquals(
                "Error queue peek:\n ",
                1,
                testQueue.peek()
        );

    }

    @Test
    public void testQueuePeekEmpty() {
        assertEquals(
                "Error queue peek on empty:\n ",
                -2147483648,
                testStack.peek()
        );
    }
}